theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true
